// components/VolumeMeter.tsx
/**
 * The Deal Volume bar: a label/value row over a rounded track whose hatched,
 * glowing fill sweeps out from the left on mount. Brand Deals introduced it;
 * Home wears it too (Alex, 2026-09-24: "I like the way the deal volume bars
 * go out"). Pure presentation: every caller passes its own numbers.
 */
const EASE = 'cubic-bezier(.2,.7,.2,1)';

export function VolumeMeter({ label, frac: rawFrac, display, hue, delay = 0 }: { label: string; frac: number; display: string; hue: string; delay?: number }) {
  const frac = Number.isFinite(rawFrac) && rawFrac > 0 ? Math.max(0.02, Math.min(1, rawFrac)) : 0.02;
  return (
    <div>
      <div className="flex items-baseline justify-between gap-3">
        <span className="text-[13.5px] text-os-muted">{label}</span>
        <span className="text-[14px] font-semibold tabular-nums">{display}</span>
      </div>
      <div className="mt-2 h-[10px] overflow-hidden rounded-full" style={{ background: 'color-mix(in oklab, var(--text) 8%, transparent)' }}>
        <div
          className="vol-fill h-full rounded-full"
          style={{
            width: `${frac * 100}%`,
            background: `linear-gradient(90deg, transparent 72%, color-mix(in oklab, ${hue} 60%, white) 100%), repeating-linear-gradient(45deg, ${hue}, ${hue} 6px, color-mix(in oklab, ${hue} 45%, transparent) 6px, color-mix(in oklab, ${hue} 45%, transparent) 12px)`,
            boxShadow: `0 0 14px color-mix(in oklab, ${hue} 45%, transparent), inset 0 0 5px color-mix(in oklab, ${hue} 55%, transparent)`,
            animation: `vol-meter-in 1.2s ${EASE} ${delay}ms both`,
          }}
        />
      </div>
    </div>
  );
}

// frontend/src/lib/founderos/kit/VolumeMeter.svelte
<!-- The Deal Volume bar (FounderOS v1 VolumeMeter.tsx): a label/value row over a
     track whose hatched, glowing fill sweeps out from the left. Unknown reads
     "unknown" over an empty dashed track instead of a zero bar. -->
<script lang="ts">
	import './kit.css';
	import { meterWidth } from './format';

	const EASE = 'cubic-bezier(.2,.7,.2,1)';

	let {
		label,
		frac,
		display,
		hue,
		delay = 0,
		compact = false
	}: {
		label: string;
		frac: number | null;
		display: string;
		hue: string;
		delay?: number;
		/** A denser row (smaller type, thinner track) for long lists like /finances' categories. */
		compact?: boolean;
	} = $props();

	const w = $derived(meterWidth(frac));
	const fill = $derived(
		w === null
			? ''
			: [
					`width: ${Math.round(w * 1000) / 10}%`,
					`background: linear-gradient(90deg, transparent 72%, color-mix(in oklab, ${hue} 60%, var(--bn-text)) 100%), repeating-linear-gradient(45deg, ${hue}, ${hue} 6px, color-mix(in oklab, ${hue} 45%, transparent) 6px, color-mix(in oklab, ${hue} 45%, transparent) 12px)`,
					`box-shadow: 0 0 14px color-mix(in oklab, ${hue} 45%, transparent), inset 0 0 5px color-mix(in oklab, ${hue} 55%, transparent)`,
					`animation: bn-vol-meter-in 1.2s ${EASE} ${delay}ms both`
				].join('; ')
	);
</script>

<div>
	<div class="flex items-baseline justify-between gap-3">
		<span class="bn-muted {compact ? 'min-w-0 truncate text-[12.5px]' : 'text-[13.5px]'}">{label}</span>
		{#if w === null}
			<span class="bn-dim {compact ? 'shrink-0 text-[12.5px]' : 'text-[14px]'} font-semibold">unknown</span>
		{:else}
			<span class="bn-text {compact ? 'shrink-0 text-[12.5px]' : 'text-[14px]'} font-semibold tabular-nums">{display}</span>
		{/if}
	</div>
	<div class="bn-vol-track {compact ? 'mt-1 h-[6px]' : 'mt-2 h-[10px]'} overflow-hidden rounded-full" data-unknown={w === null ? '' : undefined}>
		{#if w !== null}
			<div class="bn-vol-fill h-full rounded-full" style={fill}></div>
		{/if}
	</div>
</div>
