// frontend/src/lib/founderos/pages/funnel/FunnelRadial.svelte
<!-- The funnel as a circle (FounderOS v1 components/FunnelRadial.tsx): the
     journey runs outside → in. Acquisition wedges around the rim, stage rings
     pull leads inward, the core is the purchase. Same node language as the
     space; converted nodes leave their wedge for the shared core. Heavy:
     loaded lazily by FunnelGraph behind a same-aspect skeleton. -->
<script lang="ts">
	import FullscreenButton from './FullscreenButton.svelte';
	import FunnelNodeCard from './FunnelNodeCard.svelte';
	import type { FunnelNode, Segment } from './types';
	import { decayedColor, decayedOpacity, easeInOut, rnd, smoothK } from './viz';

	let {
		nodes,
		segments,
		stages,
		stageLabels,
		constants,
		initialLeadId = null
	}: {
		nodes: FunnelNode[];
		segments: Segment[];
		stages: { id: string; label: string }[];
		stageLabels: Record<string, string>;
		constants: { stallDays: number; decayDays: number; decayFadeStart: number };
		initialLeadId?: string | null;
	} = $props();

	const W = 1100;
	const H = 680;
	const CX = W / 2;
	const CY = H / 2;
	const TAU = Math.PI * 2;
	const SEG_INSET = 0.13;
	const TOP = -Math.PI / 2;
	const WEDGE = ['var(--fn-s0)', 'var(--fn-s1)', 'var(--fn-s2)', 'var(--fn-s3)', 'var(--fn-s5)', 'var(--fn-s6)'];
	const ENTER_DELAY = 500;
	const HOP_MS = 950;
	const DWELL_MS = 420;
	const GOLDEN = 2.399963;
	const staggerMs = (count: number) => Math.min(340, 5000 / Math.max(1, count));
	type Pos = { x: number; y: number };

	const segSpan = $derived(TAU / Math.max(1, segments.length));
	/** One radius per stage, outside → in; the last is the Closed core. */
	const RING = $derived(stages.map((_, i, all) => (i === all.length - 1 ? 48 : Math.round(288 - (i * (288 - 114)) / Math.max(1, all.length - 2)))));
	const CORE = $derived(RING[RING.length - 1]);

	const polar = (a: number, r: number): Pos => ({ x: Math.round((CX + Math.cos(a) * r) * 100) / 100, y: Math.round((CY + Math.sin(a) * r) * 100) / 100 });
	const wedgeAngle = (n: FunnelNode, i: number) => TOP + n.segment * segSpan + SEG_INSET + (segSpan - 2 * SEG_INSET) * rnd(i, 11);

	function bandRadius(n: FunnelNode, i: number, ring: number): number {
		if (ring >= RING.length - 1) return 6 + rnd(i, 12) * (CORE - 16);
		const outer = RING[ring] - 8;
		const inner = RING[ring + 1] + 12;
		const depth = 0.15 + 0.6 * (n.likelihood / 100) + rnd(i, 1) * 0.2;
		return outer - (outer - inner) * Math.min(0.95, depth);
	}

	function orbitTarget(n: FunnelNode, i: number, t: number): Pos {
		if (n.currentRing >= RING.length - 1) {
			const a = i * GOLDEN + t * 0.00005 * (rnd(i, 3) > 0.5 ? 1 : -1);
			return polar(a, bandRadius(n, i, RING.length - 1));
		}
		const wobble = Math.sin(t * (0.00018 + rnd(i, 2) * 0.00014) + rnd(i, 4) * TAU) * 0.09;
		const breath = Math.sin(t * 0.0009 + i * 1.3) * 2.4;
		return polar(wedgeAngle(n, i) + wobble, bandRadius(n, i, n.currentRing) + breath);
	}

	function replayPos(n: FunnelNode, i: number, tMs: number, stagger: number): Pos | null {
		const a = wedgeAngle(n, i);
		let t = tMs - (ENTER_DELAY + i * stagger);
		if (t <= 0) return polar(a, RING[0] + 46 + rnd(i, 5) * 26);
		const stops = [RING[0] + 46, ...n.rings.map((ring) => bandRadius(n, i, ring))];
		const twist = (rnd(i, 8) > 0.5 ? 1 : -1) * 0.07;
		const coreDelta = ((((i * GOLDEN) % TAU) - a + TAU * 1.5) % TAU) - Math.PI;
		for (let leg = 0; leg < stops.length - 1; leg++) {
			if (t < HOP_MS) {
				const u = easeInOut(t / HOP_MS);
				const toCore = n.rings[leg] >= RING.length - 1;
				const angle = toCore ? a + coreDelta * u : a + Math.sin(u * Math.PI) * twist;
				return polar(angle, stops[leg] + (stops[leg + 1] - stops[leg]) * u);
			}
			t -= HOP_MS;
			if (t < DWELL_MS) return polar(a, stops[leg + 1]);
			t -= DWELL_MS;
		}
		return null;
	}

	let selectedId = $state<string | null>(null);
	let root = $state<HTMLDivElement>();
	let hoverId = $state<string | null>(null);
	let nodeEls: Record<string, SVGGElement> = {};
	const pos = new Map<string, Pos>();

	$effect(() => {
		if (initialLeadId && nodes.some((n) => n.id === initialLeadId)) selectedId = initialLeadId;
	});

	$effect(() => {
		const list = nodes;
		const ids = new Set(list.map((n) => n.id));
		for (const k of [...pos.keys()]) if (!ids.has(k)) pos.delete(k);
		const place = (el: SVGGElement | undefined, p: Pos) => el?.setAttribute('transform', `translate(${p.x.toFixed(1)}, ${p.y.toFixed(1)})`);
		const reduced = typeof window.matchMedia === 'function' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
		if (reduced || typeof requestAnimationFrame !== 'function') {
			list.forEach((n, i) => place(nodeEls[n.id], orbitTarget(n, i, 0)));
			return;
		}
		let raf = 0;
		const t0 = performance.now();
		let last = t0;
		const stagger = staggerMs(list.length);
		const frame = (nowMs: number) => {
			const t = nowMs - t0;
			const k = smoothK(nowMs - last);
			last = nowMs;
			list.forEach((n, i) => {
				const el = nodeEls[n.id];
				if (!el) return;
				const target = replayPos(n, i, t, stagger) ?? orbitTarget(n, i, t);
				const prev = pos.get(n.id) ?? target;
				const next = { x: prev.x + (target.x - prev.x) * k, y: prev.y + (target.y - prev.y) * k };
				pos.set(n.id, next);
				place(el, next);
			});
			raf = requestAnimationFrame(frame);
		};
		raf = requestAnimationFrame(frame);
		return () => cancelAnimationFrame(raf);
	});

	const selected = $derived(nodes.find((n) => n.id === selectedId) ?? null);
	const anchor = $derived(selected ?? (hoverId ? (nodes.find((n) => n.id === hoverId) ?? null) : null));
	const convertedTotal = $derived(segments.reduce((s, x) => s + x.converted, 0));
</script>

{#if nodes.length === 0}
	<p class="bn-dim py-6 text-center font-mono text-[11.5px]">No journeys for this filter yet.</p>
{:else}
	<div class="fn-space-root relative" data-testid="funnel-radial" bind:this={root}>
		<FullscreenButton target={() => root} />
		{#if anchor}
			<div class="pointer-events-none absolute left-2 top-1.5 z-20 flex items-baseline gap-2 font-mono">
				<span class="bn-text text-[12px] font-semibold">{anchor.name}</span>
				<span class="bn-dim text-[9.5px] uppercase tracking-[0.12em]">{anchor.likelihood}% · {anchor.daysSinceLastTouch}d quiet</span>
			</div>
		{/if}
		<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
		<svg viewBox="0 0 {W} {H}" class="fn-radial-canvas block w-full" role="img" aria-label="Clients spiralling from their acquisition source into the conversion core" onclick={() => (selectedId = null)}>
			{#each RING.slice(0, -1) as r, s (s)}
				<g>
					<circle cx={CX} cy={CY} {r} fill="none" stroke="var(--bn-border)" stroke-dasharray="2 6" />
					<text x={CX + 9} y={CY - r + 13} fill="var(--bn-text-3)" font-size="9" font-family="var(--bn-font, monospace)" style="text-transform: uppercase; letter-spacing: 0.14em">{stages[s].label}</text>
				</g>
			{/each}
			{#each segments as seg, sIdx (seg.id)}
				{@const boundary = TOP + sIdx * segSpan}
				{@const mid = boundary + segSpan / 2}
				{@const lp = polar(mid, RING[0] + 24)}
				{@const cos = Math.cos(mid)}
				<g>
					<line x1={polar(boundary, CORE + 12).x} y1={polar(boundary, CORE + 12).y} x2={polar(boundary, RING[0]).x} y2={polar(boundary, RING[0]).y} stroke="var(--bn-border)" stroke-opacity="0.7" />
					<circle cx={polar(mid, RING[0]).x} cy={polar(mid, RING[0]).y} r="2.5" fill={WEDGE[sIdx]} />
					<text x={lp.x} y={Math.round((lp.y + Math.sin(mid) * 7 + 3) * 100) / 100} text-anchor={cos > 0.35 ? 'start' : cos < -0.35 ? 'end' : 'middle'} fill={seg.count > 0 ? 'var(--bn-text-2)' : 'var(--bn-text-3)'} font-size="10.5" font-family="var(--bn-font, monospace)" style="text-transform: uppercase; letter-spacing: 0.14em">
						{seg.label} · {seg.count}{#if seg.converted > 0}<tspan fill="var(--bn-ok)"> ✓{seg.converted}</tspan>{/if}
					</text>
				</g>
			{/each}
			<circle class="fn-hub-ring" cx={CX} cy={CY} r={CORE + 10} fill="none" stroke="var(--bn-ok)" stroke-opacity="0.45" stroke-dasharray="3 7" />
			<circle cx={CX} cy={CY} r={CORE} fill="var(--bn-surface-2)" stroke="var(--bn-ok)" stroke-opacity="0.55" stroke-width="1.2" />
			<text x={CX} y={CY - 2} text-anchor="middle" fill="var(--bn-text-2)" font-size="10" font-family="var(--bn-font, monospace)" style="text-transform: uppercase; letter-spacing: 0.18em">converted</text>
			<text x={CX} y={CY + 14} text-anchor="middle" fill="var(--bn-ok)" font-size="13" font-family="var(--bn-font, monospace)">{convertedTotal}</text>
			{#each nodes as n, i (n.id)}
				{@const color = decayedColor(WEDGE[n.segment] ?? WEDGE[0], n.decay, n.state === 'converted')}
				{@const emphasized = hoverId === n.id || selectedId === n.id}
				{@const pulses = n.state === 'converted' || (n.relationship === 'hot' && n.decay < 0.5)}
				{@const start = polar(wedgeAngle(n, i), RING[0] + 46)}
				<g
					bind:this={() => nodeEls[n.id], (el) => (nodeEls[n.id] = el)}
					data-node={n.id}
					role="button"
					tabindex="0"
					aria-label={n.person ?? n.name}
					aria-pressed={selectedId === n.id}
					onkeydown={(e) => {
						if (e.key !== 'Enter' && e.key !== ' ') return;
						e.preventDefault();
						e.stopPropagation();
						selectedId = selectedId === n.id ? null : n.id;
					}}
					transform="translate({start.x.toFixed(1)}, {start.y.toFixed(1)})"
					style="cursor: pointer"
					onmouseenter={() => (hoverId = n.id)}
					onmouseleave={() => (hoverId = null)}
					onclick={(e) => {
						e.stopPropagation();
						selectedId = selectedId === n.id ? null : n.id;
					}}
				>
					{#if pulses}
						<circle class="fn-halo" r={n.radius + 3} fill="none" stroke={color} style="animation-delay: {(i % 6) * 0.4}s; animation-duration: {n.state === 'converted' ? '3.4s' : '2.6s'}" />
					{/if}
					<circle r={n.radius + 2.5} fill="none" stroke={color} stroke-width="0.8" opacity={emphasized ? 0.9 : 0.35 * decayedOpacity(n.decay)} stroke-dasharray={n.relationship === 'cold' ? '2 3' : undefined} />
					{#if n.relationship === 'hot'}<circle r={n.radius + 5} fill="none" stroke={color} stroke-width="0.6" opacity={0.25 * decayedOpacity(n.decay)} />{/if}
					<circle r={n.radius} fill={color} stroke="var(--bn-bg)" stroke-width="1" opacity={emphasized ? 1 : decayedOpacity(n.decay)} />
					{#if emphasized}
						<text y={-n.radius - 9} text-anchor="middle" fill="var(--bn-text)" font-size="11" font-family="var(--bn-font, monospace)" style="pointer-events: none">{n.name}</text>
					{/if}
				</g>
			{/each}
		</svg>
		{#if selected}
			<FunnelNodeCard node={selected} {stageLabels} stallDays={constants.stallDays} onclose={() => (selectedId = null)} />
		{/if}
		<div class="bn-dim mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 font-mono text-[10px] uppercase tracking-wide">
			<span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full" style="background: var(--fn-s1)"></span> hue = where they came from</span>
			<span>rings run outside → in · center = purchase</span>
			<span class="flex items-center gap-1.5"><span class="h-2 w-2 rounded-full" style="background: color-mix(in oklab, var(--bn-err) 70%, var(--fn-s1)); opacity: 0.6"></span> fades red after {constants.decayFadeStart}d quiet → archive at {constants.decayDays}d</span>
			<span class="ml-auto">wedge = Trakyo first touch when attributed · untracked = word of mouth · click a node</span>
		</div>
	</div>
{/if}

// components/FunnelRadial.tsx
'use client';

/**
 * The funnel as a circle  -  the journey runs outside → in. Seven acquisition
 * wedges around the rim (Instagram incl. paid ads, YouTube, newsletter, X,
 * LinkedIn, forms, word of mouth); concentric stage rings pull leads inward;
 * the center core is the purchase. Every node is a client: it enters outside
 * the rim in its wedge, spirals in through the rings it really visited, then
 * drifts alive inside its current band. Same node language as the flow view  -
 * size = likelihood, hue = entry wedge, fade-to-red = quiet decay, green =
 * converted (and converted nodes leave their wedge for the shared core:
 * inside is inside).
 */
import { useEffect, useRef, useState } from 'react';
import { Maximize2, Minimize2 } from 'lucide-react';
import { DECAY_DAYS, DECAY_FADE_START, FUNNEL_STAGES } from '@/lib/funnel';
import { ACQUISITIONS, type FunnelRadialModel, type FunnelRadialNode } from '@/lib/funnel-radial';
import { decayedColor, decayedOpacity, easeInOut, rnd, smoothK } from '@/lib/funnel-viz';
import { FunnelNodeCard } from '@/components/FunnelNodeCard';

const W = 1100;
const H = 680;
const CX = W / 2;
const CY = H / 2;
const TAU = Math.PI * 2;
const SEG_COUNT = ACQUISITIONS.length;
const SEG_SPAN = TAU / SEG_COUNT;
/** Nodes keep this angular margin off a wedge boundary (wobble stays inside). */
const SEG_INSET = 0.13;
const TOP = -Math.PI / 2; // wedge 0 starts at 12 o'clock

/** Stage ring radii, outermost (first touch) → the converted core. */
// One radius per stage, outside → in; the last is the Closed core. Derived
// from FUNNEL_STAGES so the rings follow the stage list (four since 2026-09-24).
const RING = FUNNEL_STAGES.map((_, i, all) => (i === all.length - 1 ? 48 : Math.round(288 - (i * (288 - 114)) / Math.max(1, all.length - 2))));
const CORE = RING[RING.length - 1];

/** One hue per acquisition wedge  -  s4 (phosphor green) is skipped so no
 * wedge ever wears the conversion color. */
const WEDGE_COLOR = [
  'var(--funnel-s0)',
  'var(--funnel-s1)',
  'var(--funnel-s2)',
  'var(--funnel-s3)',
  'var(--funnel-s5)',
  'var(--funnel-s6)',
];

const ENTER_DELAY = 500; // ms before the first node departs
const HOP_MS = 950; // ring-to-ring travel time
const DWELL_MS = 420; // pause at intermediate rings
const staggerMs = (count: number) => Math.min(340, 5000 / Math.max(1, count));

type Pos = { x: number; y: number };
const GOLDEN = 2.399963;

// rounded to 2 decimals: Math.cos/sin differ in the last ULPs between V8
// builds (Node SSR vs browser), and hydration diffs cx/cy as prop mismatches
const polar = (a: number, r: number): Pos => ({
  x: Math.round((CX + Math.cos(a) * r) * 100) / 100,
  y: Math.round((CY + Math.sin(a) * r) * 100) / 100,
});

/** The fixed angle node i holds inside its wedge (jittered, never on a spoke). */
const wedgeAngle = (n: FunnelRadialNode, i: number): number =>
  TOP + n.segment * SEG_SPAN + SEG_INSET + (SEG_SPAN - 2 * SEG_INSET) * rnd(i, 11);

/**
 * The radius a node holds for a given ring: inside the band between its ring
 * and the next one in, likelihood pulling it deeper (hot ICP fit sits closer
 * to the purchase). Ring 4 = the core disc, likelihood ignored  -  they bought.
 */
function bandRadius(n: FunnelRadialNode, i: number, ring: number): number {
  if (ring >= RING.length - 1) return 6 + rnd(i, 12) * (CORE - 16);
  const outer = RING[ring] - 8;
  const inner = RING[ring + 1] + 12;
  const depth = 0.15 + 0.6 * (n.likelihood / 100) + rnd(i, 1) * 0.2;
  return outer - (outer - inner) * Math.min(0.95, depth);
}

/** Where node i drifts once it has arrived: alive, but held inside its band. */
function orbitTarget(n: FunnelRadialNode, i: number, tMs: number): Pos {
  if (n.currentRing >= RING.length - 1) {
    // converted: free slow orbit inside the shared core  -  they're in
    const a = i * GOLDEN + tMs * 0.00005 * (rnd(i, 3) > 0.5 ? 1 : -1);
    return polar(a, bandRadius(n, i, 4));
  }
  const wobble = Math.sin(tMs * (0.00018 + rnd(i, 2) * 0.00014) + rnd(i, 4) * TAU) * 0.09;
  const breath = Math.sin(tMs * 0.0009 + i * 1.3) * 2.4;
  return polar(wedgeAngle(n, i) + wobble, bandRadius(n, i, n.currentRing) + breath);
}

/** The entry replay: spiral inward through the rings this lead really visited. */
function replayPos(n: FunnelRadialNode, i: number, tMs: number, stagger: number): Pos | null {
  const a = wedgeAngle(n, i);
  let t = tMs - (ENTER_DELAY + i * stagger);
  if (t <= 0) return polar(a, RING[0] + 46 + rnd(i, 5) * 26); // waiting outside the rim
  const stops = [RING[0] + 46, ...n.rings.map((ring) => bandRadius(n, i, ring))];
  const twist = (rnd(i, 8) > 0.5 ? 1 : -1) * 0.07; // slight spiral, not a straight dive
  // shortest angular path into the core  -  never the long way around the circle
  const coreDelta = ((((i * GOLDEN) % TAU) - a + TAU * 1.5) % TAU) - Math.PI;
  for (let leg = 0; leg < stops.length - 1; leg++) {
    if (t < HOP_MS) {
      const u = easeInOut(t / HOP_MS);
      const toCore = n.rings[leg] >= RING.length - 1;
      const angle = toCore
        ? a + coreDelta * u // the last hop bends into the core
        : a + Math.sin(u * Math.PI) * twist;
      return polar(angle, stops[leg] + (stops[leg + 1] - stops[leg]) * u);
    }
    t -= HOP_MS;
    if (t < DWELL_MS) return polar(a, stops[leg + 1]);
    t -= DWELL_MS;
  }
  return null; // replay finished  -  hand over to the orbit
}

export function FunnelRadial({
  model,
  initialLeadId,
}: {
  model: FunnelRadialModel;
  /** Deep link (?lead=)  -  the attention rail pins this lead's dossier. */
  initialLeadId?: string | null;
}) {
  const { nodes, segments } = model;
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoverId, setHoverId] = useState<string | null>(null);
  // rail clicks navigate with ?lead=  -  pin that lead's dossier
  useEffect(() => {
    if (initialLeadId && nodes.some((n) => n.id === initialLeadId)) setSelectedId(initialLeadId);
  }, [initialLeadId, nodes]);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  const nodeRefs = useRef(new Map<string, SVGGElement>());
  const posRef = useRef(new Map<string, Pos>());

  useEffect(() => {
    const onChange = () => setIsFullscreen(Boolean(document.fullscreenElement));
    document.addEventListener('fullscreenchange', onChange);
    return () => document.removeEventListener('fullscreenchange', onChange);
  }, []);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    // drop eased positions for nodes that left the data (filter changes)
    const ids = new Set(nodes.map((n) => n.id));
    for (const k of [...posRef.current.keys()]) if (!ids.has(k)) posRef.current.delete(k);
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (reduced) {
      // no motion: place every node exactly where it lives
      nodes.forEach((n, i) => {
        const { x, y } = orbitTarget(n, i, 0);
        nodeRefs.current.get(n.id)?.setAttribute('transform', `translate(${x.toFixed(1)}, ${y.toFixed(1)})`);
      });
      return;
    }
    let raf = 0;
    const t0 = performance.now();
    let last = t0;
    const stagger = staggerMs(nodes.length);
    const frame = (nowMs: number) => {
      const t = nowMs - t0;
      const k = smoothK(nowMs - last);
      last = nowMs;
      nodes.forEach((n, i) => {
        const el = nodeRefs.current.get(n.id);
        if (!el) return;
        const target = replayPos(n, i, t, stagger) ?? orbitTarget(n, i, t);
        const prev = posRef.current.get(n.id) ?? target;
        const next = { x: prev.x + (target.x - prev.x) * k, y: prev.y + (target.y - prev.y) * k };
        posRef.current.set(n.id, next);
        el.setAttribute('transform', `translate(${next.x.toFixed(1)}, ${next.y.toFixed(1)})`);
      });
      raf = requestAnimationFrame(frame);
    };
    raf = requestAnimationFrame(frame);
    return () => cancelAnimationFrame(raf);
  }, [nodes]);

  if (nodes.length === 0) {
    return <p className="py-6 text-center font-mono text-[11.5px] text-os-dim">No journeys for this filter yet.</p>;
  }

  const selected = nodes.find((n) => n.id === selectedId) ?? null;
  // hover-or-pinned node → the top readout (click first, else the hovered one)
  const anchorNode = selected ?? (hoverId ? nodes.find((n) => n.id === hoverId) ?? null : null);
  const convertedTotal = segments.reduce((sum, s) => sum + s.converted, 0);

  return (
    <div ref={rootRef} className="funnel-space-root relative">
      <button
        onClick={() => {
          if (document.fullscreenElement) void document.exitFullscreen();
          else void rootRef.current?.requestFullscreen();
        }}
        aria-label={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
        className="pressable absolute right-1 top-1 z-20 rounded-sm-t border border-os-border bg-os-surface2 p-1.5 text-os-dim hover:border-os-border-strong hover:text-os-text"
      >
        {isFullscreen ? <Minimize2 className="h-3.5 w-3.5" /> : <Maximize2 className="h-3.5 w-3.5" />}
      </button>

      {/* hover readout  -  what the cursor is on, listed at the top, no click */}
      {anchorNode && (
        <div className="pointer-events-none absolute left-2 top-1.5 z-20 flex items-baseline gap-2 font-mono">
          <span className="text-[12px] font-semibold text-os-text">{anchorNode.name}</span>
          <span className="text-[9.5px] uppercase tracking-[0.12em] text-os-dim">
            {anchorNode.likelihood}% · {anchorNode.daysSinceLastTouch}d quiet
          </span>
        </div>
      )}
      <svg
        viewBox={`0 0 ${W} ${H}`}
        className="funnel-radial-canvas block w-full"
        role="img"
        aria-label="Clients spiralling from their acquisition source into the conversion core"
        onClick={() => setSelectedId(null)}
      >
        {/* stage rings  -  the journey's depth markers, outside → in */}
        {RING.slice(0, -1).map((r, s) => (
          <g key={`ring-${s}`}>
            <circle cx={CX} cy={CY} r={r} fill="none" stroke="var(--border)" strokeDasharray="2 6" />
            <text
              x={CX + 9}
              y={CY - r + 13}
              fill="var(--text-3)"
              fontSize={9}
              fontFamily="var(--font-mono)"
              style={{ textTransform: 'uppercase', letterSpacing: '0.14em' }}
            >
              {FUNNEL_STAGES[s].label}
            </text>
          </g>
        ))}

        {/* wedge spokes + rim labels */}
        {segments.map((seg, sIdx) => {
          const boundary = TOP + sIdx * SEG_SPAN;
          const mid = boundary + SEG_SPAN / 2;
          const lp = polar(mid, RING[0] + 24);
          const cos = Math.cos(mid);
          const anchor = cos > 0.35 ? 'start' : cos < -0.35 ? 'end' : 'middle';
          return (
            <g key={seg.id}>
              <line
                x1={polar(boundary, CORE + 12).x}
                y1={polar(boundary, CORE + 12).y}
                x2={polar(boundary, RING[0]).x}
                y2={polar(boundary, RING[0]).y}
                stroke="var(--border)"
                strokeOpacity={0.7}
              />
              <circle cx={polar(mid, RING[0]).x} cy={polar(mid, RING[0]).y} r={2.5} fill={WEDGE_COLOR[sIdx]} />
              <text
                x={lp.x}
                y={Math.round((lp.y + Math.sin(mid) * 7 + 3) * 100) / 100}
                textAnchor={anchor}
                fill={seg.count > 0 ? 'var(--text-2)' : 'var(--text-3)'}
                fontSize={10.5}
                fontFamily="var(--font-mono)"
                style={{ textTransform: 'uppercase', letterSpacing: '0.14em' }}
              >
                {seg.label} · {seg.count}
                {seg.converted > 0 && (
                  <tspan fill="var(--ok)"> ✓{seg.converted}</tspan>
                )}
              </text>
            </g>
          );
        })}

        {/* the core  -  inside is where they bought */}
        <circle
          className="funnel-hub-ring"
          cx={CX}
          cy={CY}
          r={CORE + 10}
          fill="none"
          stroke="var(--ok)"
          strokeOpacity={0.45}
          strokeDasharray="3 7"
        />
        <circle cx={CX} cy={CY} r={CORE} fill="var(--surface-2)" stroke="var(--ok)" strokeOpacity={0.55} strokeWidth={1.2} />
        <text
          x={CX}
          y={CY - 2}
          textAnchor="middle"
          fill="var(--text-2)"
          fontSize={10}
          fontFamily="var(--font-mono)"
          style={{ textTransform: 'uppercase', letterSpacing: '0.18em' }}
        >
          converted
        </text>
        <text x={CX} y={CY + 14} textAnchor="middle" fill="var(--ok)" fontSize={13} fontFamily="var(--font-mono)">
          {convertedTotal}
        </text>

        {/* the clients */}
        {nodes.map((n, i) => {
          const color = decayedColor(WEDGE_COLOR[n.segment], n.decay, n.state === 'converted');
          const emphasized = hoverId === n.id || selectedId === n.id;
          const pulses = n.state === 'converted' || (n.relationship === 'hot' && n.decay < 0.5);
          const start = polar(wedgeAngle(n, i), RING[0] + 46);
          return (
            <g
              key={n.id}
              ref={(el) => {
                if (el) nodeRefs.current.set(n.id, el);
                else nodeRefs.current.delete(n.id);
              }}
              transform={`translate(${start.x.toFixed(1)}, ${start.y.toFixed(1)})`}
              style={{ cursor: 'pointer' }}
              onMouseEnter={() => setHoverId(n.id)}
              onMouseLeave={() => setHoverId(null)}
              onClick={(e) => {
                e.stopPropagation();
                setSelectedId((cur) => (cur === n.id ? null : n.id));
              }}
            >
              {pulses && (
                <circle
                  className="funnel-halo"
                  r={n.radius + 3}
                  fill="none"
                  stroke={color}
                  style={{
                    animationDelay: `${(i % 6) * 0.4}s`,
                    animationDuration: n.state === 'converted' ? '3.4s' : '2.6s',
                  }}
                />
              )}
              <circle
                r={n.radius + 2.5}
                fill="none"
                stroke={color}
                strokeWidth={0.8}
                opacity={emphasized ? 0.9 : 0.35 * decayedOpacity(n.decay)}
                strokeDasharray={n.relationship === 'cold' ? '2 3' : undefined}
              />
              {n.relationship === 'hot' && (
                <circle r={n.radius + 5} fill="none" stroke={color} strokeWidth={0.6} opacity={0.25 * decayedOpacity(n.decay)} />
              )}
              <circle r={n.radius} fill={color} stroke="var(--bg)" strokeWidth={1} opacity={emphasized ? 1 : decayedOpacity(n.decay)} />
              {emphasized && (
                <text y={-n.radius - 9} textAnchor="middle" fill="var(--text)" fontSize={11} fontFamily="var(--font-mono)" style={{ pointerEvents: 'none' }}>
                  {n.name}
                </text>
              )}
            </g>
          );
        })}
      </svg>

      {selected && <FunnelNodeCard node={selected} onClose={() => setSelectedId(null)} />}

      <div className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 font-mono text-[10px] uppercase tracking-wide text-os-dim">
        <span className="flex items-center gap-1.5">
          <span className="h-2 w-2 rounded-full" style={{ background: 'var(--funnel-s1)' }} /> hue = where they came from
        </span>
        <span>rings run outside → in · center = purchase</span>
        <span className="flex items-center gap-1.5">
          <span
            className="h-2 w-2 rounded-full"
            style={{ background: 'color-mix(in oklab, var(--err) 70%, var(--funnel-s1))', opacity: 0.6 }}
          />{' '}
          fades red after {DECAY_FADE_START}d quiet → archive at {DECAY_DAYS}d
        </span>
        <span className="ml-auto">wedge = Trakyo first touch when attributed · untracked = word of mouth · click a node</span>
      </div>
    </div>
  );
}
