// frontend/src/lib/founderos/pages/agents/NeedsYouList.svelte
<!-- Needs you (FounderOS v1 components/NeedsYouList.tsx): the queue of agent
     work waiting on the operator, mounted by the Agents tab (AgentsTabs) and by Home
     (console/NeedsYou, with `fill`). It reads the SAME payload the Deliverables
     tab uses (one fetch, two views). The bridge ranks it (people first, then
     deadlines) and takes out what he already decided; his own view is layered
     on with the needs-queue module: a decision in flight, the two-hour snooze
     and the per-row unseen dot. Results confirm on the OS-wide toast stack
     (chrome/toast, mounted by the /os layout) with an undo, and a row opens
     the slide-in review panel.

     The white button is the outward call (send it, go ahead, publish): it goes
     through the bridge guard, so with FOUNDEROS_WRITES=0 it is held, says so, and
     the row stays. Dismiss is his queue's own state. Snooze holds his view in
     this browser only; no agent is told. Bulk is dismiss-only. -->
<script lang="ts">
	import { onMount } from 'svelte';
	import { ExternalLink, RefreshCw, X } from '$lib/founderos/icons';
	import { founderosFetch, isGuardRefusal } from '$lib/founderos/api';
	import Label from '$lib/founderos/kit/Label.svelte';
	import Pressable from '$lib/founderos/kit/Pressable.svelte';
	import ReviewPanel from './ReviewPanel.svelte';
	import { toast } from '$lib/founderos/chrome/toast';
	import { writeFailure } from './runerror';
	import type { Classified, Decision, DeliverableItem, DeliverablesBody } from './types';
	import {
		SNOOZE_KEY,
		ago,
		parseSnoozeMap,
		primaryOf,
		pruneSnoozed,
		queueView,
		readStore,
		snoozeItem,
		subject,
		unseenStateOf,
		unsnooze,
		writeStore,
		type OpenedMap,
		type SnoozeMap
	} from '../console/needs-queue';

	let {
		data,
		error = null,
		boardUrl = null,
		refreshing = false,
		opened,
		onOpen,
		onReload,
		fill = false
	}: {
		data: DeliverablesBody | null;
		error?: string | null;
		boardUrl?: string | null;
		refreshing?: boolean;
		/** The per-row opened store, shared with the Deliverables tab. */
		opened: OpenedMap | null;
		/** Opening a row is what clears ITS dot. */
		onOpen: (item: DeliverableItem) => void;
		onReload: () => Promise<void> | void;
		/** Home: fill the parent's box and scroll the rows inside it, so the
		    queue ends exactly where its row-mate ends (side by side only). */
		fill?: boolean;
	} = $props();

	type RowState = 'busy' | 'held';
	let local = $state<Record<string, 'approved' | 'dismissed'>>({});
	let snoozed = $state<SnoozeMap>({});
	let now = $state(Date.now());
	let confirming = $state(false);
	let failure = $state<string | null>(null);
	let rowState = $state<Record<string, RowState>>({});
	let rowError = $state<Record<string, string>>({});
	let reviewing = $state<Classified | null>(null);

	const view = $derived(queueView(data, { local, snoozed, opened, now }));
	const textOf = (c: DeliverableItem) => c.title || subject(c.name);
	const decisionOf = (id: string): Decision | undefined => data?.decisions?.find((d) => d.id === id);
	// Prod writes these borders as border-os-ok/40 etc.; Tailwind v3 cannot
	// put an opacity on a var() colour, so the class never exists and the
	// border falls back to preflight's gray-200. That light edge is what prod
	// shows, so the port draws it too (likewise no tint on overdue rows).
	const PREFLIGHT_BORDER = 'rgb(229 231 235)';
	const GLYPH_TONE: Record<string, string> = { ok: 'var(--bn-ok)', warn: 'var(--bn-warn)', err: 'var(--bn-err)', dim: 'var(--bn-text-3)' };

	onMount(() => {
		snoozed = pruneSnoozed(parseSnoozeMap(readStore(SNOOZE_KEY)));
		// Held rows come back by themselves, so the queue re-reads the clock.
		const tick = setInterval(() => (now = Date.now()), 60_000);
		return () => clearInterval(tick);
	});

	async function refresh() {
		await onReload();
		// What the reload reports as decided no longer needs the local hold.
		local = {};
	}

	/** Every handled row leaves with a toast he can take back (prod settle()). */
	function showReceipt(text: string, undo: () => void) {
		toast.ok(text, undo);
	}

	async function post(json: unknown) {
		await founderosFetch('/pages/board/deliverables/decision', { method: 'POST', json });
	}

	async function undoDecision(c: Classified) {
		try {
			await post({ id: c.id, decision: null });
		} catch (e) {
			rowError = { ...rowError, [c.id]: writeFailure(e, 'undo') };
		}
		await refresh();
	}

	/** The outward call. Not optimistic: it leaves the queue only once the
	    bridge accepted it, because a guard refusal must leave it in place. */
	async function approve(c: Classified) {
		if (rowState[c.id]) return;
		const words = primaryOf(c.ask);
		rowState = { ...rowState, [c.id]: 'busy' };
		rowError = { ...rowError, [c.id]: '' };
		try {
			await post({ id: c.id, decision: 'approved', decidedRevision: c.revision });
			local = { ...local, [c.id]: 'approved' };
			const { [c.id]: _gone, ...rest } = rowState;
			rowState = rest;
			showReceipt(`${words.done} · ${textOf(c)}`, () => void undoDecision(c));
			void refresh();
		} catch (e) {
			if (isGuardRefusal(e)) {
				rowState = { ...rowState, [c.id]: 'held' };
				toast.warn(`held · writes are off · ${textOf(c)}`);
			} else {
				const { [c.id]: _gone, ...rest } = rowState;
				rowState = rest;
				rowError = { ...rowError, [c.id]: writeFailure(e, words.label) };
			}
		}
	}

	/** Dismiss is his own queue's state: optimistic, with a receipt he can take back. */
	async function dismiss(c: Classified) {
		local = { ...local, [c.id]: 'dismissed' };
		showReceipt(`dismissed · ${textOf(c)}`, () => void undoDecision(c));
		try {
			await post({ id: c.id, decision: 'dismissed', decidedRevision: c.revision });
		} catch (e) {
			const { [c.id]: _gone, ...rest } = local;
			local = rest;
			rowError = { ...rowError, [c.id]: writeFailure(e, 'dismiss') };
			return;
		}
		void refresh();
	}

	/** "Not now" is not a decision: a two-hour hold on his own view. */
	function snooze(c: Classified) {
		snoozed = pruneSnoozed(snoozeItem(snoozed, c.id));
		writeStore(SNOOZE_KEY, snoozed);
		showReceipt(`snoozed 2h · ${textOf(c)}`, () => {
			snoozed = unsnooze(snoozed, c.id);
			writeStore(SNOOZE_KEY, snoozed);
		});
	}

	async function dismissAll(items: Classified[]) {
		confirming = false;
		const next = { ...local };
		for (const c of items) next[c.id] = 'dismissed';
		local = next;
		try {
			await post({ decision: 'dismissed', items: items.map((c) => ({ id: c.id, decidedRevision: c.revision })) });
		} catch (e) {
			failure = writeFailure(e, 'bulk dismiss');
		}
		void refresh();
	}

	function open(c: Classified) {
		onOpen(c);
		reviewing = c;
	}

	function decideFromPanel(item: DeliverableItem, kind: Decision['decision'] | null) {
		const c = reviewing;
		if (!c || c.id !== item.id) return;
		if (kind === 'approved') void approve(c);
		else if (kind === 'dismissed') {
			reviewing = null;
			void dismiss(c);
		} else void undoDecision(c);
	}
</script>

<section
	data-part="card"
	data-card="needsyou"
	class="bn-card {fill ? 'flex h-full min-h-0 flex-col' : ''}"
>
	<div data-part="card-head" class="ny-line flex flex-wrap items-center gap-x-3 gap-y-1 border-b px-4 py-2.5">
		<Label>Needs you</Label>
		<span class="bn-dim font-mono text-[10px]">
			{#if view}
				{view.queue.length} of {view.files} agent files are waiting on you{#if view.overdue > 0}<span style:color="var(--bn-err)">{` · ${view.overdue} past due`}</span>{/if}{#if view.unread > 0}<span style:color="var(--bn-accent)">{` · ${view.unread} unread`}</span>{/if}{#if view.held > 0}<span>{` · ${view.held} snoozed`}</span>{/if}{#if view.handled > 0}<span>{` · ${view.handled} handled`}</span>{/if}
			{:else if error}
				queue unreachable
			{:else}
				reading the board…
			{/if}
		</span>
		{#if boardUrl}
			<a href={boardUrl} target="_blank" rel="noreferrer" class="bn-dim bn-linky ml-auto flex items-center gap-1 font-mono text-[10px]">open board <ExternalLink class="h-3 w-3" /></a>
		{/if}
		<!-- Bulk clear is DISMISS only: on a staged item approve means SEND IT, so
		     there is no bulk approve. Two clicks, because 45 dismissals is not
		     undoable in one gesture even though each row is. -->
		{#if view && view.queue.length > 0}
			{#if confirming}
				<span class="flex shrink-0 items-center gap-1.5">
					<button type="button" class="bn-pressable ny-danger flex items-center gap-1 border px-2 py-1 font-mono text-[10px] font-bold uppercase tracking-[0.12em]" onclick={() => view && void dismissAll(view.queue)}>
						<X class="h-3 w-3" /> dismiss all {view.queue.length}
					</button>
					<button type="button" class="bn-pressable bn-dim ny-hover font-mono text-[10px] uppercase tracking-[0.12em]" onclick={() => (confirming = false)}>cancel</button>
				</span>
			{:else}
				<button type="button" class="bn-pressable bn-dim ny-hover flex shrink-0 items-center gap-1 font-mono text-[10px] uppercase tracking-[0.12em]" title="Dismiss everything shown. Nothing is sent." onclick={() => (confirming = true)}>
					<X class="h-3 w-3" /> clear all
				</button>
			{/if}
		{/if}
		<button type="button" class="bn-pressable bn-dim ny-hover flex shrink-0 items-center gap-1 font-mono text-[10px] uppercase tracking-[0.12em] disabled:opacity-40" disabled={refreshing} onclick={() => void refresh()}>
			<RefreshCw class="h-3 w-3 {refreshing ? 'animate-spin' : ''}" /> refresh
		</button>
	</div>

	<!-- The queue says who ranked it, because the order is a claim. -->
	<div class="flex items-center gap-2 px-4 pt-2">
		<span class="ny-rule h-px flex-1"></span>
		<span class="bn-dim font-mono text-[9px] uppercase tracking-[0.1em]">ranked by the Conductor · people first, then deadlines</span>
		<span class="ny-rule h-px flex-1"></span>
	</div>

	{#if failure}<p class="px-4 pt-2 font-mono text-[10.5px]" style:color="var(--bn-err)">{failure}</p>{/if}

	{#if error && !view}
		<p class="px-4 py-3 font-mono text-[11px]" style:color="var(--bn-err)">deliverables unreachable: {error}</p>
	{:else if !view}
		<p class="bn-dim px-4 py-3 font-mono text-[10.5px]">reading the board…</p>
	{:else if view.queue.length === 0}
		<div class="ny-empty m-4 grid place-items-center gap-1 border border-dashed px-4 py-8 text-center">
			<span class="text-[18px]" style:color="var(--bn-ok)">✓</span>
			<p class="bn-text text-[12.5px] font-semibold">Nothing needs you.</p>
			<p class="bn-dim font-mono text-[10px]">
				the Conductor will surface the next thing here{#if view.held > 0} · {view.held} snoozed{/if}{#if view.handled > 0} · you handled {view.handled}{/if}
			</p>
		</div>
	{:else}
		<div
			data-part="queue"
			class="mt-2 max-h-[calc(100dvh-20rem)] overflow-y-auto overscroll-contain {fill ? 'min-[1201px]:max-h-none min-[1201px]:min-h-0 min-[1201px]:flex-1' : ''}"
		>
			{#each view.queue as c (c.id)}
				{@const words = primaryOf(c.ask)}
				{@const unseen = unseenStateOf(opened, c.id, c.revision)}
				{@const state = rowState[c.id]}
				<div
					role="button"
					tabindex="0"
					data-lens="r"
					data-part="row"
					class="bn-pressable is-row ny-line grid w-full cursor-pointer grid-cols-[22px_minmax(0,1fr)] gap-2.5 border-b px-3 py-2.5 text-left last:border-b-0"
					onclick={() => open(c)}
					onkeydown={(e) => (e.key === 'Enter' || e.key === ' ') && (e.preventDefault(), open(c))}
				>
					<!-- The kind, as one character. Colour on it is status, never decoration. -->
					<span
						aria-label={c.label}
						title={c.label}
						class="ny-glyph mt-px grid h-[22px] w-[22px] place-items-center border font-mono text-[11px] font-bold"
						style:color={GLYPH_TONE[c.glyphTone] ?? GLYPH_TONE.dim}
						style:border-color={c.glyphTone === 'dim' ? 'var(--bn-border)' : PREFLIGHT_BORDER}
					>
						{c.glyph}
					</span>

					<div class="min-w-0">
						<div class="bn-dim flex items-center gap-2 font-mono text-[9.5px] uppercase tracking-[0.1em]">
							{#if unseen}
								<span
									class="h-1.5 w-1.5 shrink-0 animate-pulse"
									title={unseen === 'new' ? 'New since you last looked' : 'Rewritten since you read it'}
									aria-label={unseen === 'new' ? 'new' : 'updated'}
									style:background={unseen === 'new' ? 'var(--bn-accent)' : 'var(--bn-warn)'}
								></span>
							{/if}
							<span class="truncate">{c.meta || 'board'}</span>
							<span class="ml-auto shrink-0">{ago(c.modifiedAt, now)}</span>
						</div>

						<!-- The document's own title, not the filename. -->
						<div class="bn-text mt-0.5 text-[12.5px] font-semibold leading-snug" title={c.name}>{textOf(c)}</div>

						{#if c.summary}
							<p class="bn-muted mt-1 line-clamp-2 text-[11.5px] leading-snug">{c.summary}</p>
						{/if}

						<!-- The Conductor shows its working. -->
						<p class="bn-dim mt-1 font-mono text-[10px]">
							why here · {c.why}{#if c.deadline}<span class={c.overdue ? 'font-bold' : ''} style:color={c.overdue ? 'var(--bn-err)' : 'var(--bn-warn)'}>{c.overdue ? ' · past due ' : ' · due '}{new Date(c.deadline).toISOString().slice(11, 16)}Z</span>{/if}
						</p>

						<!-- Answerable in place; the controls stop the click before it opens the review. -->
						<!-- svelte-ignore a11y_no_static_element_interactions, a11y_click_events_have_key_events -->
						<div class="mt-2 flex flex-wrap items-center gap-1.5" onclick={(e) => e.stopPropagation()} onkeydown={(e) => e.stopPropagation()}>
							{#if state === 'held'}
								<button
									type="button"
									class="ny-held inline-flex h-[26px] items-center gap-1.5 border px-3 font-mono text-[10.5px] font-bold"
									disabled
									title="FOUNDEROS_WRITES=0: the bridge guard held this. Nothing was sent or recorded.">held: writes off</button
								>
							{:else}
								<Pressable tone="primary" disabled={!!state} aria-busy={state === 'busy'} onclick={() => void approve(c)}>
									{#if state === 'busy'}<span class="ny-spin inline-block h-[10px] w-[10px] rounded-full border-[1.5px]"></span>{words.busy}{:else}{words.label}{/if}
								</Pressable>
							{/if}
							<Pressable tone="secondary" onclick={() => void dismiss(c)}>dismiss</Pressable>
							<button
								type="button"
								data-lens="c"
								class="bn-pressable is-dark ny-snooze inline-flex h-[26px] items-center border px-2.5 font-mono text-[10.5px] font-semibold"
								title="Hold it for two hours. Nothing is sent and no agent is told."
								onclick={() => snooze(c)}>snooze</button
							>
							<span class="bn-dim ml-auto font-mono text-[9.5px] uppercase tracking-[0.1em]">
								{c.label}{#if c.alsoAs && c.alsoAs.length > 0}{` · also .${c.alsoAs.join(', .')}`}{/if}
							</span>
						</div>
						{#if rowError[c.id]}
							<p class="mt-1 font-mono text-[10px]" style:color="var(--bn-err)">{rowError[c.id]}</p>
						{/if}
					</div>
				</div>
			{/each}
		</div>
	{/if}
</section>

<!-- Read the work, then approve or dismiss it, without leaving the page. -->
<ReviewPanel item={reviewing} decision={reviewing ? decisionOf(reviewing.id) : undefined} onDecide={decideFromPanel} onClose={() => (reviewing = null)} />

<style>
	.ny-line {
		border-color: var(--bn-border);
	}
	.ny-hover:hover:not(:disabled) {
		color: var(--bn-text);
	}
	/* border-os-err/50 + hover:bg-os-err/10 in prod: both no-ops (see PREFLIGHT_BORDER) */
	.ny-danger {
		border-color: rgb(229 231 235);
		border-radius: var(--bn-r-ctl, 6px);
		color: var(--bn-err);
	}
	.ny-rule {
		background: var(--bn-border);
	}
	.ny-empty {
		border-color: var(--bn-border);
		border-radius: var(--bn-r-panel, 10px);
	}
	.ny-glyph {
		border-radius: var(--bn-r-ctl, 6px);
	}
	.ny-snooze {
		border-color: var(--bn-border);
		border-radius: var(--bn-r-ctl, 6px);
		background: var(--bn-bg);
		color: var(--bn-text-2);
	}
	.ny-held {
		border-color: color-mix(in oklab, var(--bn-warn) 50%, transparent);
		border-radius: var(--bn-r-ctl, 6px);
		background: color-mix(in oklab, var(--bn-warn) 10%, transparent);
		color: var(--bn-warn);
		cursor: not-allowed;
	}
	.ny-spin {
		border-color: var(--bn-accent-ink);
		border-right-color: transparent;
		animation: bn-om-spin 0.8s linear infinite;
	}
</style>

// components/NeedsYouList.tsx
'use client';

import { ExternalLink, RefreshCw, X } from 'lucide-react';
import { useState } from 'react';
import { AsyncButton } from '@/components/AsyncButton';
import { useToast } from '@/components/Toaster';
import type { UnseenState } from '@/lib/deliverables-opened';
import { needsYou, type ApprovalKind, type Classified } from '@/lib/board-approvals';
import { partitionByDecision } from '@/lib/deliverable-decisions';
import { revisionOf } from '@/lib/deliverable-revision';
import type { DeliverableGroup, DeliverableItem } from '@/lib/board-deliverables';
import type { DecisionKind, DeliverableDecision } from '@/lib/schemas';
import { Label } from '@/components/terminal';

/**
 * Needs You  -  the queue of agent work waiting on Alex.
 *
 * Alex, 2026-08-20: "I need a way to see that I'm getting tasks done or a
 * place I can go to verify work ... I want to be able to approve tasks that
 * agents need my input on."
 *
 * It reads the SAME payload the Deliverables tab already polls  -  one fetch, two
 * views  -  and filters it through the agents' own naming vocabulary. On the real
 * board that turns 92 undifferentiated files into 46 that are actually asking
 * him for something, 40 of which are replies staged and never sent.
 *
 * Mock 3a turned the row from a link into the answer itself: kind glyph, where
 * it came from, what it is, why the Conductor surfaced it, and the two calls in
 * place. The row still opens the review panel for the full text, but he should
 * never have to open it to say yes.
 *
 * Deliberately not a second poller and not a second source of truth: if it ever
 * disagreed with Deliverables about what exists, both would stop being trusted.
 */
const GLYPH_TONE: Record<Classified['glyphTone'], string> = {
  ok: 'border-os-ok/40 text-os-ok',
  warn: 'border-os-warn/40 text-os-warn',
  err: 'border-os-err/50 text-os-err',
  dim: 'border-os-border text-os-dim',
};

/** What the white button says, per kind. "Approve" is not a verb he uses. */
const PRIMARY: Record<ApprovalKind, { label: string; busy: string; done: string }> = {
  staged: { label: 'send it', busy: 'sending', done: 'sent' },
  decision: { label: 'go ahead', busy: 'recording', done: 'called' },
  gate: { label: 'unblock', busy: 'opening', done: 'open' },
  request: { label: 'approve', busy: 'recording', done: 'approved' },
  draft: { label: 'publish', busy: 'publishing', done: 'published' },
  done: { label: 'ok', busy: 'saving', done: 'ok' },
  output: { label: 'ok', busy: 'saving', done: 'ok' },
};

const when = (iso: string): string => {
  const ms = Date.now() - Date.parse(iso);
  if (!Number.isFinite(ms)) return '';
  const m = Math.floor(ms / 60000);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  return h < 24 ? `${h}h ago` : `${Math.floor(h / 24)}d ago`;
};

/** Strip the agent's bookkeeping so the row reads as a subject, not a filename. */
function subject(name: string): string {
  return name
    .replace(/\.[a-z0-9]+$/i, '')
    .replace(/^STAGED-/i, '')
    .replace(/-?DELIVER-BEFORE-\d{4}Z/i, '')
    .replace(/-?\d{4}-\d{2}-\d{2}(T\d{4}Z)?$/i, '')
    .replace(/-(COMMENT|PATCH)$/i, '')
    .replace(/[-_]+/g, ' ')
    .trim();
}

/**
 * The dot, on the piece of content itself.
 *
 * Alex, 2026-08-22: "can you put the dot of what I haven't seen any updates
 * to on the actual piece of content that was created so I can know that that
 * was created?"
 *
 * NEW means it appeared since he last opened anything here. UPDATED means he
 * read it and an agent has rewritten it since, which on this board happens a
 * lot: two files were retracted by their own authors today.
 */
function UnseenDot({ state }: { state: UnseenState }) {
  if (!state) return null;
  return (
    <span
      title={state === 'new' ? 'New since you last looked' : 'Rewritten since you read it'}
      aria-label={state === 'new' ? 'new' : 'updated'}
      className={`h-1.5 w-1.5 shrink-0 animate-pulse ${
        state === 'new' ? 'bg-os-accent' : 'bg-os-warn'
      }`}
    />
  );
}

function Row({
  c,
  onOpen,
  unseen,
  onDecide,
  onSnooze,
  onWake,
}: {
  c: Classified;
  onOpen: (i: DeliverableItem) => void;
  unseen: UnseenState;
  onDecide: (id: string, decision: DecisionKind | null, revision: string) => void | Promise<void>;
  onSnooze: (i: DeliverableItem) => void;
  onWake: (i: DeliverableItem) => void;
}) {
  const toast = useToast();
  const rev = revisionOf(c);
  const text = c.title || subject(c.name);
  const words = PRIMARY[c.ask];

  /**
   * Every handled row leaves with a receipt he can take back. The undo clears
   * the decision rather than writing an opposite one, so the file returns to
   * the queue exactly as the agent left it.
   */
  const settle = async (decision: DecisionKind, said: string) => {
    await onDecide(c.id, decision, rev);
    toast.ok(`${said} · ${text}`, () => void onDecide(c.id, null, rev));
  };

  return (
    <div
      role="button"
      data-lens="r"
      tabIndex={0}
      onClick={() => onOpen(c)}
      onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && (e.preventDefault(), onOpen(c))}
      data-part="row"
      className={`pressable is-row grid w-full cursor-pointer grid-cols-[22px_minmax(0,1fr)] gap-2.5 border-b border-os-border px-3 py-2.5 text-left last:border-b-0 ${
        c.overdue ? 'bg-os-err/[0.06]' : ''
      }`}
    >
      {/* The kind, as one character. Colour on it is status, never decoration. */}
      <span
        aria-label={c.label}
        title={c.label}
        className={`mt-px grid h-[22px] w-[22px] place-items-center rounded-ctl border font-mono text-[11px] font-bold ${GLYPH_TONE[c.glyphTone]}`}
      >
        {c.glyph}
      </span>

      <div className="min-w-0">
        <div className="flex items-center gap-2 font-mono text-[9.5px] uppercase tracking-[0.1em] text-os-dim">
          <UnseenDot state={unseen} />
          <span className="truncate">{c.meta || 'board'}</span>
          <span className="ml-auto shrink-0">{when(c.modifiedAt)}</span>
        </div>

        {/* The title is the document's own, not the filename. Alex,
            2026-08-21: "That's not fucking English I can't read it." */}
        <div className="mt-0.5 text-[12.5px] font-semibold leading-snug text-os-text" title={c.name}>
          {text}
        </div>

        {c.summary && (
          <p className="mt-1 line-clamp-2 text-[11.5px] leading-snug text-os-muted">{c.summary}</p>
        )}

        {/* Mock 3a: the Conductor shows its working. */}
        <p className="mt-1 font-mono text-[10px] text-os-dim">
          why here · {c.why}
          {c.deadline && (
            <span className={c.overdue ? ' font-bold text-os-err' : ' text-os-warn'}>
              {c.overdue ? ' · past due ' : ' · due '}
              {new Date(c.deadline).toISOString().slice(11, 16)}Z
            </span>
          )}
        </p>

        {/* Answerable in place. The row opens the review panel, so the controls
            have to stop the click before it gets there. AsyncButton's onClick
            takes no event, hence the wrapper rather than a handler argument. */}
        <div
          className="mt-2 flex flex-wrap items-center gap-1.5"
          onClick={(e) => e.stopPropagation()}
          onKeyDown={(e) => e.stopPropagation()}
        >
          <AsyncButton
            run={() => settle('approved', words.done)}
            tone="primary"
            busyLabel={words.busy}
            doneLabel={words.done}
          >
            {words.label}
          </AsyncButton>
          <AsyncButton
            run={() => settle('dismissed', 'dismissed')}
            tone="secondary"
            busyLabel="dismissing"
            doneLabel="dismissed"
          >
            dismiss
          </AsyncButton>
          <button
            onClick={() => {
              onSnooze(c);
              toast.ok(`snoozed 2h · ${text}`, () => onWake(c));
            }}
            title="Hold it for two hours. Nothing is sent and no agent is told."
            data-lens="c"
            className="pressable is-dark inline-flex h-[26px] items-center rounded-ctl border border-os-border bg-os-bg px-2.5 font-mono text-[10.5px] font-semibold text-os-muted"
          >
            snooze
          </button>
          <span className="ml-auto font-mono text-[9.5px] uppercase tracking-[0.1em] text-os-dim">
            {c.label}
            {c.alsoAs && c.alsoAs.length > 0 && ` · also .${c.alsoAs.join(', .')}`}
          </span>
        </div>
      </div>
    </div>
  );
}

export function NeedsYouList({
  groups,
  refreshing,
  onRefresh,
  boardUrl,
  decisions,
  onOpen,
  unseenOf,
  onDismissMany,
  onDecide,
  snoozedOf,
  onSnooze,
  onWake,
}: {
  groups: DeliverableGroup[] | null;
  refreshing: boolean;
  onRefresh: () => void;
  boardUrl: string | null;
  decisions: Record<string, DeliverableDecision>;
  onOpen: (i: DeliverableItem) => void;
  unseenOf: (i: DeliverableItem) => UnseenState;
  onDismissMany: (items: DeliverableItem[]) => void;
  onDecide: (id: string, decision: DecisionKind | null, revision: string) => void | Promise<void>;
  snoozedOf: (i: DeliverableItem) => boolean;
  onSnooze: (i: DeliverableItem) => void;
  onWake: (i: DeliverableItem) => void;
}) {
  const [confirming, setConfirming] = useState(false);
  if (groups === null) {
    return <p className="font-mono text-[10.5px] text-os-dim">reading the board…</p>;
  }

  const files = groups.flatMap((g) => g.items).filter((i) => i.kind === 'file');
  // What he has already approved or dismissed leaves the queue  -  and comes back
  // by itself if the agent rewrites it (see lib/deliverable-decisions).
  const { open: ranked, decided } = partitionByDecision(needsYou(files), decisions);
  // "Not now" is not a decision; it is a hold on his own view for two hours.
  const queue = ranked.filter((c) => !snoozedOf(c));
  const held = ranked.length - queue.length;
  const overdue = queue.filter((c) => c.overdue).length;
  const unread = queue.filter((c) => unseenOf(c) !== null).length;

  return (
    <section data-part="card" className="rounded-panel border border-os-border bg-os-surface">
      <div data-part="card-head" className="flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-os-border px-4 py-2.5">
        <Label>Needs you</Label>
        <span className="font-mono text-[10px] text-os-dim">
          {queue.length} of {files.length} agent files are waiting on you
          {overdue > 0 && <span className="text-os-err"> · {overdue} past due</span>}
          {unread > 0 && <span className="text-os-accent"> · {unread} unread</span>}
          {held > 0 && <span className="text-os-dim"> · {held} snoozed</span>}
          {decided.length > 0 && <span className="text-os-dim"> · {decided.length} handled</span>}
        </span>
        {boardUrl && (
          <a
            href={boardUrl}
            target="_blank"
            rel="noreferrer"
            className="ml-auto flex items-center gap-1 font-mono text-[10px] text-os-dim linky"
          >
            open board <ExternalLink className="h-3 w-3" />
          </a>
        )}
        {/* Bulk clear (Alex, 2026-08-22: "bulk clear as well"). DISMISS only:
            on a staged item approve means SEND IT, so there is deliberately no
            bulk approve. Two clicks, because 45 dismissals is not undoable in
            one gesture even though each row individually is. */}
        {queue.length > 0 &&
          (confirming ? (
            <span className="flex shrink-0 items-center gap-1.5">
              <button
                onClick={() => {
                  onDismissMany(queue);
                  setConfirming(false);
                }}
                className="pressable flex items-center gap-1 rounded-ctl border border-os-err/50 px-2 py-1 font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-os-err hover:bg-os-err/10"
              >
                <X className="h-3 w-3" /> dismiss all {queue.length}
              </button>
              <button
                onClick={() => setConfirming(false)}
                className="pressable font-mono text-[10px] uppercase tracking-[0.12em] text-os-dim hover:text-os-text"
              >
                cancel
              </button>
            </span>
          ) : (
            <button
              onClick={() => setConfirming(true)}
              title="Dismiss everything shown. Nothing is sent."
              className="pressable flex shrink-0 items-center gap-1 font-mono text-[10px] uppercase tracking-[0.12em] text-os-dim hover:text-os-text"
            >
              <X className="h-3 w-3" /> clear all
            </button>
          ))}
        <button
          onClick={onRefresh}
          disabled={refreshing}
          className="pressable flex shrink-0 items-center gap-1 font-mono text-[10px] uppercase tracking-[0.12em] text-os-dim hover:text-os-text disabled:opacity-40"
        >
          <RefreshCw className={`h-3 w-3 ${refreshing ? 'animate-spin' : ''}`} /> refresh
        </button>
      </div>

      {/* Mock 3a: the queue says who ranked it, because the order is a claim. */}
      <div className="flex items-center gap-2 px-4 pt-2">
        <span className="h-px flex-1 bg-os-border" />
        <span className="font-mono text-[9px] uppercase tracking-[0.1em] text-os-dim">
          ranked by the Conductor · people first, then deadlines
        </span>
        <span className="h-px flex-1 bg-os-border" />
      </div>

      {queue.length === 0 ? (
        <div className="m-4 grid place-items-center gap-1 rounded-panel border border-dashed border-os-border px-4 py-8 text-center">
          <span className="text-[18px] text-os-ok">✓</span>
          <p className="text-[12.5px] font-semibold text-os-text">Nothing needs you.</p>
          <p className="font-mono text-[10px] text-os-dim">
            the Conductor will surface the next thing here
            {held > 0 && ` · ${held} snoozed`}
            {decided.length > 0 && ` · you handled ${decided.length}`}
          </p>
        </div>
      ) : (
        <div className="mt-2 max-h-[calc(100dvh-20rem)] overflow-y-auto overscroll-contain">
          {queue.map((c) => (
            <Row
              key={c.id}
              c={c}
              onOpen={onOpen}
              unseen={unseenOf(c)}
              onDecide={onDecide}
              onSnooze={onSnooze}
              onWake={onWake}
            />
          ))}
        </div>
      )}
    </section>
  );
}
