// components/SkillsGrid.tsx
'use client';

/**
 * The skill catalog as one filtered card wall (mock 5g): a text filter, the
 * All / Claude Code / Operator / Draft chips with live counts, and cards that
 * read eyebrow (source · scope) / status / title / two-line description /
 * footer path-or-owner. Click a card to expand its real SKILL.md in a reader.
 * The full doc loads on demand (GET /api/skills/[slug]) so the page ships
 * light, unless a card carries inline markdown (the seeded fallback).
 * 2026-09-24: the wall is a Brand Deals SlabCard, its filters the slab pills.
 */
import { useEffect, useState, type ReactNode } from 'react';
import {
  X,
  Download,
  Flame,
  Code2,
  Image as ImageIcon,
  FileSignature,
  Hammer,
  ClipboardList,
  SearchCheck,
  Plug,
  Target,
  Clapperboard,
  Cog,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';
import { SlabCard, chipClass } from '@/components/slab';

export type SkillCard = {
  id: string; // slug  -  also the /api/skills/[slug] key
  name: string;
  group: string;
  kind: 'claude' | 'operator';
  description: string;
  meta: string; // source path or owner  -  the card footer
  filePath: string;
  status?: 'live' | 'learning' | 'planned';
  markdown?: string; // inline (fallback); otherwise fetched by id
};

const STATUS: Record<string, string> = { live: 'var(--ok)', learning: 'var(--warn)', planned: 'var(--text-3)' };

type Filter = 'All' | 'Claude Code' | 'Operator' | 'Draft';
const isDraft = (c: SkillCard) => c.status != null && c.status !== 'live';
const matches = (c: SkillCard, f: Filter) =>
  f === 'All' ? true : f === 'Draft' ? isDraft(c) : f === 'Claude Code' ? c.kind === 'claude' : c.kind === 'operator';

/** What sits above the title: the card's source and scope. */
const eyebrowOf = (c: SkillCard) =>
  c.kind === 'claude' ? `Claude Code · ${c.id.includes(':') ? 'plugin' : 'user'}` : c.group;

/** The tool/nature each skill runs on, as an icon. */
function skillIcon(card: SkillCard): LucideIcon {
  if (card.group === 'Firecrawl') return Flame;
  switch (card.id) {
    case 'codex':
      return Code2;
    case 'nano-banana':
      return ImageIcon;
    case 'proposal-generator':
      return FileSignature;
    case 'mcp-builder':
      return Plug;
    case 'build':
      return Hammer;
    case 'spec':
      return ClipboardList;
    case 'review':
      return SearchCheck;
  }
  switch (card.group.replace(/^Operator · /, '')) {
    case 'Sales':
      return Target;
    case 'Content':
      return Clapperboard;
    case 'Ops':
      return Cog;
    case 'Engineering':
      return Code2;
    default:
      return Sparkles;
  }
}

function inline(text: string): ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((p, i) => {
    if (p.startsWith('**') && p.endsWith('**')) return <strong key={i} className="font-semibold text-os-text">{p.slice(2, -2)}</strong>;
    if (p.startsWith('`') && p.endsWith('`')) return <code key={i} className="rounded bg-os-surface2 px-1 font-mono text-[11px] text-os-accent">{p.slice(1, -1)}</code>;
    return <span key={i}>{p}</span>;
  });
}

function Markdown({ src }: { src: string }) {
  const out: ReactNode[] = [];
  let fence: string[] | null = null;
  let k = 0;
  for (const line of src.split('\n')) {
    if (line.trim().startsWith('```')) {
      if (fence) {
        out.push(<pre key={k++} className="my-2 overflow-x-auto rounded-md border border-os-border bg-os-bg p-3 font-mono text-[11px] leading-relaxed text-os-muted">{fence.join('\n')}</pre>);
        fence = null;
      } else fence = [];
      continue;
    }
    if (fence) { fence.push(line); continue; }
    if (/^#\s/.test(line)) out.push(<h1 key={k++} className="mb-1 mt-4 text-[16px] font-bold">{inline(line.slice(2))}</h1>);
    else if (/^##\s/.test(line)) out.push(<h2 key={k++} className="mb-1 mt-3 font-mono text-[11px] font-bold uppercase tracking-widest text-os-dim">{inline(line.slice(3))}</h2>);
    else if (/^###\s/.test(line)) out.push(<h3 key={k++} className="mt-2 text-[12.5px] font-semibold">{inline(line.slice(4))}</h3>);
    else if (/^---\s*$/.test(line)) out.push(<hr key={k++} className="my-2.5 border-os-border" />);
    else if (/^\s*[-*]\s/.test(line))
      out.push(<div key={k++} className="flex gap-2 text-[12.5px] leading-relaxed text-os-muted"><span className="text-os-accent">·</span><span>{inline(line.replace(/^\s*[-*]\s/, ''))}</span></div>);
    else if (line.trim() === '') out.push(<div key={k++} className="h-2" />);
    else out.push(<p key={k++} className="text-[12.5px] leading-relaxed text-os-muted">{inline(line)}</p>);
  }
  if (fence) out.push(<pre key={k++} className="my-2 overflow-x-auto rounded-md border border-os-border bg-os-bg p-3 font-mono text-[11px] leading-relaxed text-os-muted">{fence.join('\n')}</pre>);
  return <div>{out}</div>;
}

export function SkillsGrid({ cards, sourceNote, i = 6 }: { cards: SkillCard[]; sourceNote: string; i?: number }) {
  const [viewing, setViewing] = useState<SkillCard | null>(null);
  const [md, setMd] = useState<string | null>(null);
  const [filter, setFilter] = useState<Filter>('All');
  const [query, setQuery] = useState('');

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setViewing(null);
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, []);

  const open = async (card: SkillCard) => {
    setViewing(card);
    if (card.markdown != null) {
      setMd(card.markdown);
      return;
    }
    setMd(null); // loading
    try {
      const res = await fetch(`/api/skills/${encodeURIComponent(card.id)}`);
      const body = (await res.json()) as { markdown?: string; error?: string };
      setMd(body.markdown ?? `SKILL.md could not be read (${body.error ?? res.status}).`);
    } catch {
      setMd('SKILL.md could not be read.');
    }
  };

  const FILTERS: Filter[] = ['All', 'Claude Code', 'Operator', 'Draft'];
  const q = query.trim().toLowerCase();
  const shown = cards.filter(
    (c) =>
      matches(c, filter) &&
      (q === '' || `${c.name} ${c.description} ${c.meta} ${c.group}`.toLowerCase().includes(q)),
  );

  const ViewingIcon = viewing ? skillIcon(viewing) : Sparkles;

  /** Save the open SKILL.md: real skills stream from the API, inline docs download as a blob. */
  const download = (card: SkillCard) => {
    if (card.markdown == null) {
      window.location.href = `/api/skills/${encodeURIComponent(card.id)}?download=1`;
      return;
    }
    const blob = new Blob([card.markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${card.id}-SKILL.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // The reader modal sits OUTSIDE the SlabCard: the card's rise/lift transforms
  // would otherwise become the containing block of its position: fixed.
  return (
    <>
      <SlabCard
        i={i}
        className="mt-6"
        title="Skills"
        sub={`${shown.length} of ${cards.length}`}
        action={FILTERS.map((f) => (
          <button key={f} onClick={() => setFilter(f)} className={chipClass(filter === f)}>
            {f} {cards.filter((c) => matches(c, f)).length}
          </button>
        ))}
      >
        <div className="flex flex-wrap items-center gap-3 px-6 pb-4 pt-4">
          <p className="min-w-0 flex-1 font-mono text-[11px] text-os-dim">{sourceNote}</p>
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="filter skills"
            className="h-[34px] w-52 rounded-full border border-os-border bg-os-bg px-4 font-mono text-[12px] text-os-text placeholder:text-os-dim focus:border-os-border-strong focus:outline-none"
          />
        </div>

        <div className="border-t border-os-border px-6 pb-6 pt-5">
          {shown.length === 0 ? (
            <p className="py-4 text-center text-[12.5px] text-os-dim">
              no skills match{q ? ` "${query.trim()}"` : ''} · clear the filter to see all {cards.length}
            </p>
          ) : (
            <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
              {shown.map((c) => {
                const Icon = skillIcon(c);
                const status = c.status ?? 'live';
                return (
                  <button
                    key={c.id}
                    onClick={() => open(c)}
                    title={`${c.name} · open SKILL.md`}
                    data-lens="r"
                    className="pressable is-row group flex flex-col gap-2 rounded-[10px] border border-os-border bg-os-bg p-4 text-left"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span className="truncate font-mono text-[9.5px] uppercase tracking-[0.14em] text-os-dim">
                        {eyebrowOf(c)}
                      </span>
                      <span className="flex shrink-0 items-center gap-1.5 font-mono text-[9.5px] uppercase tracking-[0.1em] text-os-dim">
                        <span className="h-1.5 w-1.5 rounded-full" style={{ background: STATUS[status] }} />
                        {status}
                      </span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Icon className="h-4 w-4 shrink-0 text-os-accent" strokeWidth={1.8} />
                      <span className="min-w-0 flex-1 truncate text-[13.5px] font-bold group-hover:text-os-text">{c.name}</span>
                    </div>
                    <p className="line-clamp-2 min-h-[30px] text-[11px] leading-snug text-os-dim">{c.description}</p>
                    <div className="truncate border-t border-os-border pt-2 font-mono text-[9.5px] text-os-dim">{c.meta}</div>
                  </button>
                );
              })}
            </div>
          )}
        </div>
      </SlabCard>

      {viewing && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-6 backdrop-blur-sm" onClick={() => setViewing(null)}>
          <div className="flex max-h-[82vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl border border-os-border-strong bg-os-surface" onClick={(e) => e.stopPropagation()}>
            <div className="flex shrink-0 items-center justify-between border-b border-os-border px-5 py-3">
              <span className="flex min-w-0 items-center gap-2 font-mono text-[11px] text-os-dim">
                <ViewingIcon className="h-3.5 w-3.5 shrink-0 text-os-accent" />
                <span className="truncate">{viewing.filePath}</span>
              </span>
              <span className="flex shrink-0 items-center gap-3">
                <button
                  onClick={() => download(viewing)}
                  title="Download SKILL.md"
                  className="pressable flex items-center gap-1.5 rounded-md border border-os-border px-2 py-1 font-mono text-[10px] uppercase tracking-widest text-os-dim hover:border-os-border-strong hover:text-os-text"
                >
                  <Download className="h-3 w-3" />
                  skill.md
                </button>
                <button onClick={() => setViewing(null)} aria-label="Close" className="pressable shrink-0 text-os-dim hover:text-os-text">
                  <X className="h-4 w-4" />
                </button>
              </span>
            </div>
            <div className="overflow-y-auto px-5 py-4">
              {md === null ? (
                <p className="animate-pulse font-mono text-[11px] text-os-dim">loading SKILL.md…</p>
              ) : (
                <Markdown src={md} />
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// frontend/src/lib/founderos/pages/skills/SkillsGrid.svelte
<!-- The skill catalog as one filtered card wall (FounderOS v1 components/SkillsGrid.tsx,
     mock 5g, 2026-09-24 a Brand Deals SlabCard): the card is titled "Skills"
     with "n of m" beside it and the All / Claude Code / Operator / Draft chips
     as its action; under the head sit the source note and the text filter,
     then the wall. Cards read eyebrow / status / title / two-line description
     / footer. A card opens its SKILL.md in a reader (fetched from
     /pages/skills/:slug unless the card carries it inline) with a download. -->
<script lang="ts">
	import type { Component } from 'svelte';
	import {
		ClipboardList,
		Clapperboard,
		CodeXml,
		Cog,
		Download,
		FilePenLine,
		Flame,
		Hammer,
		Image,
		Plug,
		SearchCheck,
		Sparkles,
		Target,
		X
	} from '$lib/founderos/icons';
	import { founderosFetch, founderosUrl } from '$lib/founderos/api';
	import { SlabCard, chipClass } from '$lib/founderos/kit';
	import SkillMarkdown from './SkillMarkdown.svelte';
	import { eyebrowOf, FILTERS, filterCards, iconKeyOf, matches, type Filter, type IconKey } from './skills';
	import type { SkillCard } from './types';

	let {
		cards,
		sourceNote,
		i = 6
	}: {
		cards: SkillCard[];
		sourceNote: string;
		i?: number;
	} = $props();

	// lucide-svelte ships legacy class components.
	type Icon = Component<{ class?: string; strokeWidth?: number }>;
	const ICONS: Record<IconKey, Icon> = {
		flame: Flame,
		code: CodeXml,
		image: Image,
		signature: FilePenLine,
		plug: Plug,
		hammer: Hammer,
		spec: ClipboardList,
		review: SearchCheck,
		target: Target,
		content: Clapperboard,
		ops: Cog,
		sparkles: Sparkles
	} as unknown as Record<IconKey, Icon>;
	const XIcon = X as unknown as Icon;
	const DownloadIcon = Download as unknown as Icon;

	const STATUS: Record<string, string> = { live: 'var(--bn-ok)', learning: 'var(--bn-warn)', planned: 'var(--bn-text-3)' };

	let filter = $state<Filter>('All');
	let query = $state('');
	let viewing = $state<SkillCard | null>(null);
	let md = $state<string | null>(null);

	const shown = $derived(filterCards(cards, filter, query));
	const counts = $derived(Object.fromEntries(FILTERS.map((f) => [f, cards.filter((c) => matches(c, f)).length])) as Record<Filter, number>);
	const ViewingIcon = $derived(viewing ? ICONS[iconKeyOf(viewing)] : ICONS.sparkles);

	async function open(card: SkillCard) {
		viewing = card;
		if (card.markdown != null) {
			md = card.markdown;
			return;
		}
		md = null; // loading
		try {
			const body = await founderosFetch<{ markdown?: string }>(`/pages/skills/${encodeURIComponent(card.id)}`);
			if (viewing?.id === card.id) md = body.markdown ?? 'SKILL.md could not be read (empty response).';
		} catch (e) {
			if (viewing?.id === card.id) md = `SKILL.md could not be read (${e instanceof Error ? e.message : 'unreachable'}).`;
		}
	}

	/** Operator skills carry their SKILL.md inline: save it as a file. */
	function downloadInline(card: SkillCard) {
		const blob = new Blob([card.markdown ?? ''], { type: 'text/markdown;charset=utf-8' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${card.id}-SKILL.md`;
		a.click();
		URL.revokeObjectURL(url);
	}

</script>

<svelte:document onkeydown={(e) => e.key === 'Escape' && (viewing = null)} />

<SlabCard {i} class="mt-6" title="Skills" sub={`${shown.length} of ${cards.length}`}>
	{#snippet action()}
		{#each FILTERS as f (f)}
			<button type="button" onclick={() => (filter = f)} data-lens="c" class={chipClass(filter === f)} aria-pressed={filter === f}
				>{f} {counts[f]}</button
			>
		{/each}
	{/snippet}
	<div class="flex flex-wrap items-center gap-3 px-6 pb-4 pt-4">
		<p class="bn-dim min-w-0 flex-1 font-mono text-[11px]">{sourceNote}</p>
		<input
			bind:value={query}
			placeholder="filter skills"
			class="bn-text h-[34px] w-52 rounded-full border px-4 font-mono text-[12px] bn-border placeholder:text-[var(--bn-text-3)] focus:border-[var(--bn-border-strong)] focus:outline-none"
			style="background: var(--bn-bg)"
		/>
	</div>

	<div class="border-t px-6 pb-6 pt-5 bn-border">
		{#if shown.length === 0}
			<p class="bn-dim py-4 text-center text-[12.5px]">
				no skills match{query.trim() ? ` "${query.trim()}"` : ''} · clear the filter to see all {cards.length}
			</p>
		{:else}
			<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
				{#each shown as c (c.id)}
					{@const CardIcon = ICONS[iconKeyOf(c)]}
					{@const status = c.status ?? 'live'}
					<button
						type="button"
						onclick={() => open(c)}
						title={`${c.name} · open SKILL.md`}
						data-lens="r"
						class="bn-pressable is-row group flex flex-col gap-2 rounded-[10px] border p-4 text-left bn-border"
						style="background: var(--bn-bg)"
					>
						<div class="flex items-center justify-between gap-2">
							<span class="bn-dim truncate font-mono text-[9.5px] uppercase tracking-[0.14em]">{eyebrowOf(c)}</span>
							<span class="bn-dim flex shrink-0 items-center gap-1.5 font-mono text-[9.5px] uppercase tracking-[0.1em]">
								<span data-part="status-dot" class="h-1.5 w-1.5 rounded-full" style={`background: ${STATUS[status]}`}></span>{status}
							</span>
						</div>
						<div class="flex items-center gap-2">
							<span class="bn-accent shrink-0"><CardIcon class="h-4 w-4" strokeWidth={1.8} /></span>
							<span class="bn-text min-w-0 flex-1 truncate text-[13.5px] font-bold">{c.name}</span>
						</div>
						<p class="bn-dim line-clamp-2 min-h-[30px] text-[11px] leading-snug">{c.description}</p>
						<div class="bn-dim truncate border-t pt-2 font-mono text-[9.5px] bn-border">{c.meta}</div>
					</button>
				{/each}
			</div>
		{/if}
	</div>
</SlabCard>

<!-- The reader sits outside the SlabCard, whose rise/lift transform would
     otherwise become the containing block of position: fixed. -->
{#if viewing}
	{@const card = viewing}
	<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
	<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-6 backdrop-blur-sm" onclick={() => (viewing = null)}>
		<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
		<div
			role="dialog"
			aria-modal="true"
			aria-label={`${card.name} SKILL.md`}
			tabindex="-1"
			class="flex max-h-[82vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl border"
			style="border-color: var(--bn-border-strong); background: var(--bn-surface)"
			onclick={(e) => e.stopPropagation()}
		>
			<div class="flex shrink-0 items-center justify-between border-b px-5 py-3 bn-border">
				<span class="bn-dim flex min-w-0 items-center gap-2 font-mono text-[11px]">
					<span class="bn-accent shrink-0"><ViewingIcon class="h-3.5 w-3.5" /></span>
					<span class="truncate">{card.filePath}</span>
				</span>
				<span class="flex shrink-0 items-center gap-3">
					{#if card.markdown == null}
						<a
							href={founderosUrl(`/pages/skills/${encodeURIComponent(card.id)}?download=1`)}
							title="Download SKILL.md"
							class="bn-pressable bn-dim flex items-center gap-1.5 rounded-md border px-2 py-1 font-mono text-[10px] uppercase tracking-widest bn-border hover:text-[var(--bn-text)]"
							><DownloadIcon class="h-3 w-3" />skill.md</a
						>
					{:else}
						<button
							type="button"
							onclick={() => downloadInline(card)}
							title="Download SKILL.md"
							class="bn-pressable bn-dim flex items-center gap-1.5 rounded-md border px-2 py-1 font-mono text-[10px] uppercase tracking-widest bn-border hover:text-[var(--bn-text)]"
							><DownloadIcon class="h-3 w-3" />skill.md</button
						>
					{/if}
					<button type="button" onclick={() => (viewing = null)} aria-label="Close" class="bn-pressable bn-dim shrink-0 hover:text-[var(--bn-text)]"><XIcon class="h-4 w-4" /></button>
				</span>
			</div>
			<div class="overflow-y-auto px-5 py-4">
				{#if md === null}
					<p class="bn-dim animate-pulse font-mono text-[11px]">loading SKILL.md…</p>
				{:else}
					<SkillMarkdown src={md} />
				{/if}
			</div>
		</div>
	</div>
{/if}
